# Generated by Django 3.2.8 on 2021-11-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todoitem_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='details',
        ),
    ]
